### PR TITLE
improved performance of most for loops

### PR DESCRIPTION
**Pull request by bvandevliet**
Summary of the issue:

For loops are set up in such a way that the length value to compare the index against is recalculated on each pass. This is a minor performance issue that can be very easily improved.

Description outlining how this pull request resolves the issue:

All for loops that declare an index variable in the loop itself now also declare a fixed length variable once and use that variable to compare the index against. This covers not all for loops but most of them. The others would need a little extra attention as their index variable was declared before the loop which requires a different approach for declaring the length variable.

### CODE REVIEW

**Review by mhutchie — CHANGES_REQUESTED** [review]
Hi @bvandevliet,

Thanks for making these code improvements! I make code improvements in every release to improve performance, readability, extensibility, or to add value in any way for users. I think it's extremely important to do this, and I'm pleased you feel a similar way by raising this PR. I also really appreciate that you've taken the time to improve the extension.

---

Two considerations I have are:
* I try to write the code in a way that anyone with any level of development experience can understand (i.e. readability). This is important because I want the community to be able improve the extension if they want to. For the majority of this last year, I've been moving away from `for` loops in favour of some of the newer JavaScript array methods (e.g. `filter`, `find`, `forEach`, `map` etc.), where it makes sense to do so (e.g. arrays are small so the performance penalty is negligible). This is to improve readability, and reduce foundational loop logic already implemented in the JavaScript runtime. I've got multiple other ongoing readability initiatives that I'm steadily progressing with, ensuring I'm always moving in the right direction.
* In working on a product with so many users (both individuals and corporate), it's critical to ensure high quality releases with little-to-no bugs. I find it annoying with the volume of bugs introduced in new releases of Visual Studio Code and other extensions, so I try to do everything I can to prevent this. One of the processes I've put in place is that before any release, I do a complete review of all code changes, and physically test each line of code that changed in an installed release candidate of the extension. This is in addition to all testing done as features are implemented. I know this is somewhat overkill, however it's one of the main reasons there have been so few bugs introduced in this extension.

---

I did some benchmarking in the current Visual Studio Code runtime to test the performance improvement of changing from fetching the array length on each iteration, to fetching it up-front into a variable. In all of these benchmarks, the length of the array was a key factor:
* For arrays with length less than 10, the difference was negligible, and within hardware noise.
* For arrays with length less than 500, the improvement is fractions of a microsecond per entire loop (not per iteration).
* For arrays with length up to a few thousand, the improvement was still much less than a microsecond per entire loop (not per iteration).

Although this benchmarking could get different results on different hardware, the performance improvement across all these options is effectively negligible. I did run it on the scale of multiple billions of loop iterations to obtain reasonable averages. Even if it was off by two orders of magnitude, it is still sub 0.01 milliseconds gains, which is unperceivable to users.

All of the loops you changed in this PR fall into one of these three categories (the majority are in the first two length categories). It's also clear in the benchmarks that far more can be gained by optimising the body of each loop iteration (which is where the majority of the time is spent).

---

I'd prefer if you removed the bulk of these changes, keeping only the changes on loops operating on arrays that would realistically have length greater than a few hundred (e.g. the loops over all commits etc.). This seems to be where most value can be achieved by making this change, and I think it would definitely be worth including in the extension. I suggest this approach due to the combination of all of the following reasons (if only one of these reasons applied, I would have already merged this PR):
* On small arrays, the performance improvement is negligible.
* I think the change makes the code less readable. I'd much prefer to continue making it more readable by utilising array methods where it makes sense to do so (even if it has slightly worse performance).
* Introducing 109 changes to loop conditions, means 109 more pieces of logic to test before release. Although looking at this change in isolation it looks like it's trivial with minimal risk, and after reviewing your code I'm confident it's correct, by the time you have 10 large overlapping features / changes for a release, testing everything thoroughly becomes much more time consuming.
* The next release already has a significant amount of code improvements included in it - I generally try to spread code improvements across releases to reduce risk and decrease the testing complexity.

---

FYI: In the future, before making such large changes I'd encourage you reach out before you start work (as mentioned in `CONTRIBUTING.md` and the pull request template). It's always good to have clear communication on what's being worked on, to allow better co-ordination and to brainstorm the details before time is spent implementing changes. I'm pretty responsive to quick questions and discussions, it's only larger responses like this that takes me longer. I also have [Discord](https://discord.gg/ZRRDYzt), which is another method for discussion (if raising an issue may or may not be necessary).

**Comment by bvandevliet** [comment]
Hi @mhutchie,

Thanks for reviewing my PR and your detailed explanation. To be honest, I didn't have and took the time to study the code carefully. When I was scanning it (mostly out of curiosity), the for loops where the first thing that struck me. So I thought let's run a replace all using a regex and see what happens. This PR is the result. If you'd ask me, the drawback on code readability is negligible, but also is the performance gain as you've proven though. While I'm confident it's a zero-risk upgrade and more according best practices, I agree it's probably more worthwhile to have a proper look into moving to newer array functions and improving the bodies of each loop iteration. That said, I think it's best to either keep it as it is for now and wait for the more effective improvements to be made, or merge all the for loops in this PR at once, but not just a few. But I also understand you have to be careful with so many users ;)

**Comment by mhutchie** [comment]
Hi @bvandevliet,

I agree that the readability drawback is minimal, however it does require an additional variable to be defined (that breaks-up the readers flow). When I Google "JavaScript for loop array", the first five results all use the `for (let i = 0; i < array.length; i++) {` notation. This is a strong indicator to me that this is how most people are taught `for` loops, and would be most familiar with (even if it is slightly worse performance).
* https://www.w3schools.com/js/js_loop_for.asp
* https://love2dev.com/blog/javascript-for-loop-foreach/
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration
* https://www.freecodecamp.org/news/javascript-loops-explained-for-loop-for/
* https://medium.com/chingu/looping-over-arrays-and-objects-in-javascript-57e1188c1ba2

It's just not an option to merge these 107 code changes throughout the entire extension, considering the majority have negligible benefit. Please let me know which of the following two options you want to take:
1. Adjust this PR to remove the bulk of these changes, keeping only the changes on loops operating on arrays that would realistically have length greater than a few hundred (e.g. the loops over all commits etc.). I expect roughly 10 loops would fall into this category. By focusing on these higher-value loops first, they can be released straight away (and not have to wait for all the other loops to be completed).
2. We close this PR, and over-time the for loops will be naturally be migrated to the newer array methods, as features are implemented that modify those parts of the codebase. This approach has worked very well over the last year, and there has already been a significant migration away from `for` loops. Making bulk changes to migrate to the array methods in a single PR is equally not an option for many of the same reasons, especially when the same result can naturally be achieved over time in a far more manageable way.

Regardless of your choice, I thank you for taking the time to work on this PR.

**Comment by bvandevliet** [comment]
Hi @mhutchie,

Then, let's leave it for now to let it being improved over time. I was happy to raise this PR. You're doing a great job with this extension! 

Kr Bob

**Pull request closed without merging**
