### PR TITLE
Add configuration of repository remotes - Change remotes url

### PR DESCRIPTION
**Pull request by rbalet**
Issue Number / Link: #95 / https://github.com/mhutchie/vscode-git-graph/issues/95

Summary of the issue:
Wanted to be able to change the remote URL and also add a settings icon for another future configurations.

Description outlining how this pull request resolves the issue:
-  Add 
  -  cogs icon on the top right
  -  Drop down menu
  -  Change remote url 

Problem
I have another way of formatting things and I couldn't do the same as yours (I should have disable to much extension and automatisation). So I juste ship as is.
Hope it would be OK.

### CODE REVIEW

**Comment by rbalet** [comment]
And sorry, I deleted the old pullRequest when I was squashing the commits,
There was you comment

Thanks for implementing this feature request and contributing to this extension, awesome work & it's much appreciated! It's great to have all of the core code working end-to-end, great job!

The outstanding items before this can be merged is:

It will need to support multiple remotes in the front end.
The names of the remotes of the repo are already available in GitGraphView.gitRemotes in the front end, which is sourced in getRemotes and then passed to the front end in the loadCommits response message. GitGraphView.gitRemotes can be used to allow the user to view/change each remote uri.
It would be nice if the front end can display the existing url of each remote (used as the default value of the text input), so the user knows exactly what they are changing.
To get the urls, getRemotes can be expanded to return an array of objects containing the name and url of each remote, instead of just names (current behaviour). Some minor front end code changes in main.ts would be required so it can use the new data format.
If you'd like to have a go at any of these it would be much appreciated, although I'm also happy to do them if you'd prefer. You've already saved me a huge amount of time! I'm committed to finalising the implementation of search / filtering commits for the next release first, but afterwards I can work on this PR depending on what you can do.

It's easy for me to automatically reformat the code back to the current style, no problem at all.

FYI: Today I released 1.8.0, which compared to the point you branched from has a variety of minor improvements, and a bug fix from the unreleased improved error handling in a0567874, which I picked up in my pre-release testing. Specifically, an unnecessary error message was displayed when the diff view is opened and one side doesn't exist (e.g. file was added/deleted). Apologies if you've been finding it annoying. Depending on how frequently you're using the "change remotes url" functionality, you may prefer to install the 1.8.0 release until this PR is merged for your normal use, and just compile & run in the Extension Development Host any more work you do on this PR.

**Comment by rbalet** [comment]
I could manage to do the 
"display the existing url of each remote"

Cause:
Had trouble to understand why [GitCommitData](https://github.com/mhutchie/vscode-git-graph/blob/aeb54b8302e04b2128efeb6740b00908077a9f54/src/types.ts#L9-L15) contain two remotes attribute and the which one I should use.

I Tried to use only the one inside the [GitCommitNode](https://github.com/mhutchie/vscode-git-graph/blob/aeb54b8302e04b2128efeb6740b00908077a9f54/src/types.ts#L22-L32) attribute, but the UI remote name would'nt be displayed anymore

**Comment by rbalet** [comment]
Hi there!
I've changed the GitCommitData and the getRemotes to return an object with  the name and the url but I couldn't manage to passe these url to the [input value](https://github.com/rbalet/vscode-git-graph/blob/aed3ee4760940657c272bd0ee0c2692d4d939aee/web/main.ts#L154).
I have actually no Idea how I should do that, but since we already can choose the remote & change the url I hope it would be enough for the moment.
If not, I don't know if I have the knowledge to help you there...
Regards

**Comment by mhutchie** [comment]
Thank you for all of the extra work you have done on this PR! It's much appreciated!

I didn't have any time to work on the extension this last week after finishing the find widget, and since I only had a small amount of time yesterday I just did a variety of other small feature requests so I could get the find widget released for everyone to use.

At the end of this week when I have time to work on the extension again I'll do some finishing touches on this PR and get it merged for the next release.

Thanks again for your awesome work!

**Comment by mhutchie** [comment]
Last weekend I had to work on askpass integration (prompting the user for remote credentials if they are requested by commands that communicate with a remote), as this was preventing a user from using any of the Git actions that communicate with remotes. This meant I had do another release before I could get to work on this.

This last week I've started work on this item, and have & will continue working on:
* Some UI changes.
* Adding support for different remote urls for fetch and push.
* Allowing remotes to be added.
* Allowing remotes to be deleted.

I'll close this PR now as I've used everything I can from it, and will have to do a squash merge anyway when I finalise the parts mentioned above.

Thank you for the considerable amount of work you have put into this, it has saved me a lot of time and meant this feature will be available to Git Graph users sooner. I'll acknowledge your work in the releases changelog, like I do with all community members that implement functionality for the extension.

**Pull request closed without merging**
