### PR TITLE
Make controls and table header sticky on top

### PR DESCRIPTION
**Pull request by vfonic**
I've forked your extension and my extension will go in a different direction.

I'm just sending you back some of the changes I've made to your code, while the code is still similar to your extension.

Not sure if you'd like to merge this PR or not, up to you.

<details>
<summary>Here's a screenshot</summary>
Screen Shot 2019-05-09 at 21 49 48
</details>

PS I'm not sure how much more I'll be able to port back to your extension, but feel free to take stuff from here: https://github.com/vfonic/vscode-ada-lightbulb

Why different extension?
I'd like to customize the extension to my needs. Maybe it will end up being similar, although I believe it will pretty soon become quite different.
I also switched from Typescript to Javascript. I still didn't jump board to Typescript. :)

### CODE REVIEW

**Comment by vfonic** [comment]
I think there are some issue with this PR:

- [ ] Loading spinner should be pushed down (it appears slightly below the sticky header)
- [ ] scrolling to expanded commit seems to be incorrect, or maybe this was an existing bug

**Comment by mhutchie** [comment]
Thanks for these changes! Like the other PR, I can't have a proper look at the PR until I finish my uni exams.

The scrolling for the expanded commit view is [here](https://github.com/mhutchie/vscode-git-graph/blob/master/web/main.ts#L699-L711) in the `showCommitDetails` function. Given the controls & table header changes you've made, I think you'll just need to make a small change to each of the calculations.

**Comment by mhutchie** [comment]
@vfonic, in response to `Why different extension?`:

Almost all of your todo features are functionality that I already intend & would like to have in Git Graph, and implement as I, and the community, have the capacity to do so. The reason they aren't already present is because I implement functionality in order of priority from the community. I don't implement the functionality I want or would benefit me first, I implement functionality the community wants (although community members are welcome to contribute functionality they like, and I then merge them as soon as possible). The main benefit I see of open source software is for communities to develop a solution together maximising available functionality, far beyond an individual or small team can.

If you would like to contribute any of the functionality you want, your welcome to do so here by PR's, or by raising issues so they can be prioritised and implemented by myself and others of this community.

I've corrected the [License](https://github.com/mhutchie/vscode-git-graph/blob/master/LICENSE) of this project to reflect my expectations, which is not the standard MIT license. This comment is to notify you of the changes, which are that: although you are `granted permission to use, copy, modify & merge` your own forks of the project for your own use, you are not permitted to `publish, distribute, sublicense, and/or sell copies of the Software`.

**Comment by vfonic** [comment]
Re: `Why different extension`

Hey @mhutchie!

I'm sorry you see this this way.

I'm happy that we have similar ideas for which functionalities would be great to have in this kind of VS Code extension.

I'm also looking into taking bits of code from other VS Code git extensions. What happens if they all change their licenses? What happens if we all decide to forbid "to publish, distribute, sublicense, and/or sell copies of the Software."? (ok, that's a bit too dramatic)

I want to build this extension because I want to have a great git visual tool for myself. I'm willing to share that back with the community, if anyone wants to use. I don't care if the tool is mine or yours. I just want the tool. And I think I'll build it faster this way.
I think that's the beauty and power of truly open source software.
Feel free to take any parts of my project and port them back to yours. If you need any help and have any questions, let me know, I'd love to help you integrate the features back into your project.

I added the MIT license and added you there as a copyright notice. I hope that fixes that part. The new license you wrote only applies to the newer versions of your code, starting from the moment that license was introduced. I'll therefore not take any more of your code, as I don't want to break the license.

Take care,
Viktor

https://twitter.com/elonmusk/status/1126653097114198016

**Comment by mhutchie** [comment]
@vfonic,

When you breached the original MIT licence in `vscode-ada-lightbulb` by not complying with the statement `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software`, at [this commit](https://github.com/vfonic/vscode-ada-lightbulb/tree/cf67ea7548513194d709864b29aa178547b8b950), you have no right to continue using it.

I amended the license of the Git Graph codebase while you were breaching it, and notified you of this change when it took affect. In order for your derivate work `vscode-ada-lightbulb` to now comply with the licenced usage of the Git Graph codebase, you are required to adopt the current licence agreement as it was in place before you complied with the original MIT licence. This does not affect your ability to "I want to build this extension because I want to have a great git visual tool for myself", it is just prevents you from publishing it to the Visual Studio Marketplace.

**Comment by mhutchie** [comment]
@vfonic, after consulting the GitHub copyright policies:

As I'm the copyright holder, because you breached the original MIT policy by deliberately removing the licence agreement from your copy `vscode-ada-lightbulb` of the `vscode-git-graph` repository, I have the right to to request that this content is permanently removed from GitHub and not published. All prior versions of `vscode-ada-lightbulb` before commit 94a081c2 still breach the original MIT licence.

I request that you do so, or, you may state in the license of `vscode-ada-lightbulb` that you will not `publish, distribute, sublicense, and/or sell copies derivative works of the Software`. As I've previously said, I have no problem with you modifying Git Graph for your personal use, I just don't want you to publish it yourself. Let me know when you have taken one of these actions, if you do not, I will go through the formal GitHub DMCA Take-down Process.

**Comment by mhutchie** [comment]
Thank you for raising a pull request for these changes, under normal circumstances I would have happily merged these changes.

As you breached the licence of the Git Graph extension with your derivate work `vscode-ada-lightbulb` as discussed above, and have still not complied with either option I (the copyright holder) have given you, ignoring them, I will not be accepting this pull request.

**Pull request closed without merging**
