### PR TITLE
Use custom diff tool

### PR DESCRIPTION
**Pull request by JimmyBondie**
Hi all,

I added a possibility to use a custom diff tool to review your changes.
It would be nice if you can merge it to the official branch because I would like to use another diff tool than vscode.

### CODE REVIEW

**Review by mhutchie — CHANGES_REQUESTED** [review]
The capability was previously requested in #469, and [this comment of mine](https://github.com/mhutchie/vscode-git-graph/issues/469#issuecomment-788282862) explains why I didn't want to include it in the extension.

I still don't particularly want to include it for the same reasons, however if you're willing to action the following changes, I'd happily include it in the extension. I've already spent ~5 hours (since you raised this PR) just to work out how it should be implemented, and the intricacies of difftool integrations to work out what's feasible - I don't want to spend much more time on it.

Changes:

* Just like "Open External Directory Diff" in the Commit Details View, this capability should be based on the Git configuration of `diff.tool`, `diff.guitool`, and be automatically available to the user if they have configured a difftool in Git.
    * This prevents the user from having to duplicate configuration, and learn the custom syntax you've created for `diffSettings.cmdCallDiffTool`. Instead, you can make use of Git's `difftool.<tool>.path` and `difftool.<tool>.cmd`, and follow the same default behaviour as Git if they're not provided.
    * This capability can be made available as an additional action in the File Context Menu of files in the Commit Details View. It should only be included if the user has configured a difftool (eliminating the need for `diffSettings.useCustomDiffTool`).
* Instead of `git-graph.diffSettings.revisionTempDir`, you can just use [`os.tmpdir()`](https://nodejs.org/api/os.html#os_os_tmpdir), to save the user having to configure it.
* It should integrate with DiffDocProvider for retrieving the file contents, instead of running a custom Git command outside of DataSource.
* It should run the command in a Visual Studio Code Terminal if `diff.tool` is configured, or in a spawned child process if `diff.guitool` is configured. (`diff.guitool` takes precedence over `diff.tool`)

In the future, please follow the instructions in [CONTRIBUTING.md](https://github.com/mhutchie/vscode-git-graph/blob/develop/CONTRIBUTING.md#contributing-to-development) for raising a new feature request, or commenting on an existing feature request, before you start writing code - this would have saved you the rework, as you would have had the necessary information before you started.

**Comment by JimmyBondie** [comment]
Indeed, these are great approaches!
I implemented them all and the tests are also running.

What do you think?

**Review by mhutchie — CHANGES_REQUESTED** [review]
Thank you for making those changes so far!

Instead of modifying the "View Diff" action, please create a new "View Diff in External Difftool" action on the File Context Menu of files in the Commit Details View, specifically for this new functionality. The actions for this menu are defined [here](https://github.com/JimmyBondie/vscode-git-graph/blob/40f13b1fd41e4a0188b714d08f566350ac88481e/web/main.ts#L2971-L3020). This will make it consistent with how most other Git UI's support external difftools. The other advantage of doing this, is that the front-end already has the result of `DataSource.getConfig` & `DataSource.getRemotes` stored in it's `GitGraphView.gitConfig` property, so it saves having to re-fetch this data.

You can extend the `GitRepoConfig` returned by `DataSource.getConfig`, so that instead of just providing the name of the diffTool & guiDiffTool, it also provides `difftool.<tool>.path` and `difftool.<tool>.cmd` - something like this:

```
export interface DifftoolConfig {
	readonly name: string;
        readonly path: string | null;
        readonly cmd: string | null;
}

export interface GitRepoConfig {
	readonly branches: GitRepoConfigBranches;
	readonly diffTool: DifftoolConfig | null;
	readonly guiDiffTool: DifftoolConfig | null;
	readonly pushDefault: string | null;
	readonly remotes: ReadonlyArray<GitRepoSettingsRemote>;
	readonly user: {
		readonly name: {
			readonly local: string | null,
			readonly global: string | null
		},
		readonly email: {
			readonly local: string | null,
			readonly global: string | null
		}
	};
}
```


The new request and response would look something like:
```
export interface RequestViewDiffInExternalDifftool extends RepoRequest {
	readonly command: 'viewDiffInExternalDifftool';
	readonly fromHash: string;
	readonly toHash: string;
	readonly oldFilePath: string;
	readonly newFilePath: string;
	readonly type: GitFileStatus;
	readonly difftool: DifftoolConfig;
	readonly isGui: boolean;
}
export interface ResponseViewDiffInExternalDifftool extends ResponseWithErrorInfo {
	readonly command: 'viewDiffInExternalDifftool';
}
```

Instead of creating a new instance of `DiffDocProvider`, you should be able to pass [the existing instance](https://github.com/JimmyBondie/vscode-git-graph/blob/40f13b1fd41e4a0188b714d08f566350ac88481e/src/extension.ts#L47) via `CommandManager` and `GitGraphView`. This saves a new instance from being created every time the user wants to view a diff in the difftool, and your function having to dispose it after it's used.

Please have a look at how [`openGitTerminal`](https://github.com/JimmyBondie/vscode-git-graph/blob/40f13b1fd41e4a0188b714d08f566350ac88481e/src/utils.ts#L566-L584) works, so that you can properly make use of `PATH` and `cwd`.

You'll need to support when `difftool.<tool>.cmd` isn't provided (using the standard default behaviour).

You'll need to handle when the URI's returned by `encodeDiffDocUri` have the `file` scheme.

From what I can see, Git and every other tool I've checked uses file names similar to `path.join(os.tmpdir(), getNonce() + '_' + oldFilePath.substring(oldFilePath.lastIndexOf('/') + 1))`. It's probably worth following the same pattern for consistency.

FYI: You can run the unit tests locally by running `npm run test` in a terminal, or running the "Run Unit Tests" task in Visual Studio Code.

**Comment by JimmyBondie** [comment]
Hi, I could implement some things you mentioned but since I actually do not have so much time, I cannot implement everything.

It would be very kind if you are fine with this approach and upload it to the official version because I really would like to use it.
Thanks! :-)

**Pull request closed without merging**
