### PR TITLE
Pull changes when checking out remote branch

### PR DESCRIPTION
**Pull request by luisherranz**
Fixes: #297

**Summary of the issue:**
Pull changes when checking out a remote branch that has an existing branch.

**Description outlining how this pull request resolves the issue:**
I have added the `pullBranch` action after the checkout.

**Still missing:**
The UI doesn't reflect the changes after a couple of seconds so maybe it needs to force a refresh, but I haven't found the way to do so. If you point me out, I can finish the PR.

### CODE REVIEW

**Comment by mhutchie** [comment]
Thanks for raising this pull request!

I'm currently busy doing final release preparations for Git Graph 1.23.0 (which will be released this weekend). I'll have a look at this PR in more detail once I've finished the release, as I'll have to think about the best design for implementing it as the extension should complete the checkout, then pull the branch. This sequencing is not guaranteed by your current implementation (as there are some underlying asynchronous JavaScript functions that run), even it it does work most of the time.

I expect the final solution will need to sequence these operations [here](https://github.com/mhutchie/vscode-git-graph/blob/master/src/gitGraphView.ts#L177-L180) (instead of in the front-end), similar to how the `addTag` action does [here](https://github.com/mhutchie/vscode-git-graph/blob/master/src/gitGraphView.ts#L158-L162). This will also automatically cause the UI to refresh as expected.

**Comment by luisherranz** [comment]
Awesome. Let me know once you release the 1.23.0 version and I'll look into this again if it's needed.

**Comment by mhutchie** [comment]
Apologies for the long delay for me to get back to this, I was quite unwell which meant that I had to delay releasing Git Graph 1.23.0 for a few weeks.

I've implemented this change in [5c0c7d41](https://github.com/mhutchie/vscode-git-graph/commit/5c0c7d415ac0bebed9bdf1873a625e4774ebe4e5). I ended up having to write a different solution to the one you raised in this pull request (based on what I mentioned in my previous reply), in order for it to work asynchronously and refresh upon completion.

This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.0](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.0), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Comment by luisherranz** [comment]
No problem. Thanks for the feature @mhutchie! 😄

**Comment by luisherranz** [comment]
😍😍😍 Thanks @mhutchie !!

Screenshot 2020-07-02 at 10 11 26

**Pull request closed without merging**
