### PR TITLE
Support for "Remote Development"

### PR DESCRIPTION
**Pull request by Dontar**
Issue Number / Link: #83 

Summary of the issue:
Add support for "Remote Development"

In order to make the extension compatible with "Remote Development" I in-lined the content of the `media` folder with the html of WebviewPanel.

### CODE REVIEW

**Comment by mhutchie** [comment]
Thanks for this suggestion & initial implementation! It would definitely be nice to support the upcoming "Remote Development" functionality. After having a look at this PR, it will definitely result in a performance decrease due to the three blocking synchronous file system operations on the initial load. A possible solution would be to convert each file system operation to be async, wrap them each in a promise, and then await for Promise.all of them, then you can just pass in the file contents inline to the Webview content as you have done.

I'd like to focus on the six outstanding new features that I have committed to releasing by the end of this week (24/05/2019), as "Remote Development" isn't available in the standard Visual Studio Code (for at least the next two weeks). If I have spare time before the 1.6.0 release, or as soon as 1.6.0 is released, I'll look into ways alternative ways of supporting "Remote Development" without introducing a noticeable performance overhead (I think the Promise.all solution should be fine if you're interested in trying it out in this PR).

I intend to release 1.7.0 by the end of the following week (31/05/2019), which would make "Remote Development" definitely available before it is released in the standard Visual Studio Code if it isn't able to make 1.6.0 (which I'll still aim for).

Thanks again!

**Comment by Dontar** [comment]
Hi @mhutchie
I managed to implement an a promisified variant. I also had to raise the `@types/node` version in order to be able to use the promisified version of the native node `fs` module. Despite that it is still in Experimental stage, I have never had any issues with it. Also couldn't help myself and fixed small irregularity in `viewDiff` method.

Best regards

PS: Thanks for the awesome and extremely helpful extension. Couldn't live without it. :)

**Comment by mhutchie** [comment]
Awesome work, thank you for making those changes!

I've completed three of the six feature requests I mentioned yesterday due for delivery this week, once I finish of the last three I'll merge this PR so it can be included in this weeks 1.6.0 release.

**Comment by Dontar** [comment]
Hi again @mhutchie,
A friend of mine pointed out that I'm supposed to give you a written consent to include my contributions. To be honest I'm not sure how the legal side in our area of expertise actually works. Anyway, you have my full consent to use everything I contribute as long that use is compliant  with whatever legal regulations are in place in that regard.

Best regards. :)

**Comment by mhutchie** [comment]
Thank you for all your hard work with this PR!

When I tested Git Graph it in all three "Remote Development" environments, I found that I needed to make a number of other small changes for some edge cases. Your contributions saved me a significant amount of time, and definitely allowed this feature to be released this week in 1.6.0. Without your help I wouldn't have been able to get "Remote Development" support done, and it would have had to be released next week.

The commit including my changes is [c0b9ca60](https://github.com/mhutchie/vscode-git-graph/commit/c0b9ca60e2b23cec2aecc618cc32850b59bc9922). The commit references your help in completing it, and you'll be acknowledged in the final changelog entry for 1.6.0.

I intend to release 1.6.0 in the next day, after I do thorough release testing.

Thanks again!

**Pull request closed without merging**
