### PR TITLE
#175 Select/Unselect all branches in dropdown when clicking on 'show …

### PR DESCRIPTION
**Pull request by thmatot**
…all' to allow to unselect branch

Issue Number / Link: (If this is a minor change, then an issue does not need to be created and this line can be deleted.)

Summary of the issue:

Description outlining how this pull request resolves the issue:

### CODE REVIEW

**Comment by mhutchie** [comment]
Thanks for raising this pull request! Awesome work!

From what I can see your changes look perfect. When I’m back home I’ll do some of my own testing and then merge it.

**Comment by mhutchie** [comment]
Everything you’ve written is working perfectly, thank you!

After using it, I’m considering whether this behaviour should be triggered on “consecutive clicks” or “double clicks”. I’m just going to get some feedback on this from some users I use for user testing of the extension, and then will then merge this.

**Comment by mhutchie** [comment]
The feedback that I received suggested that having different user actions (click and double click) for each behaviour was easier to understand. Clicking dropdown options maintains the same behaviour as before, whereas double clicking "Show All" now selects/unselects all dropdown elements.

I just did a small refactoring on top of your two changes to support single and double clicks, and then I manually merged this pull request in commit [72ad5090](https://github.com/mhutchie/vscode-git-graph/commit/72ad509048b73cdccea77c8bb68525e38215b345).

Thank you for implementing this feature, it's a great addition to Git Graph!

In the release documentation & changelog I acknowledge contributions made by community members. Could you please confirm the spelling of your first name?
* [Thibaut Matot (@thmatot)](https://github.com/thmatot)!
* [Thibault Matot (@thmatot)](https://github.com/thmatot)!

**Comment by thmatot** [comment]
Hi, 
Thanks for the approval,

you can use Thibault Matot (@thmatot)

**Pull request closed without merging**
